FROM node:15.14.0-alpine3.10 AS builder
WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install

COPY . ./

RUN ng build --prod

FROM nginx:1.20.2-alpine
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
# COPY config/nginx.conf /etc/nginx/nginx.conf
COPY config/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]