FROM node:15.14.0-alpine3.10 AS builder
WORKDIR /myweb

COPY package.json package-lock.json ./
RUN npm install

ENV PATH="./node_modules/.bin:$PATH"
COPY . ./
RUN npm run build 

FROM nginx:1.20.2-alpine
COPY --from=builder dist /usr/share/nginx/html
COPY config/nginx.conf  /etc/nginx/conf.d/default.conf