apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: training
  labels:
    customer: training
    environment: development
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: localhost:5000/backend
          name: backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 200
            periodSeconds: 10
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: SPRING_REDIS_PORT
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: SPRING_REDIS_PASSWORD
            - name: APP_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: APP_TOKEN_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: training
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: backend
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: training
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80