apiVersion: v1
data:
#  kafka_host: VEJE
#  kafka_port: VEJE
#  db_host: VEJE
#  db_port: VEJE
#  db_username: VEJE
#  db_password: VEJE
#  redis_host: VEJE
#  redis_port: VEJE
#  redis_password: VEJE
#  jwt_secret: VEJE
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTAuMTA5LjU0LjE3MDo1NDMyL2JhY2tlbmQ=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: ZEhuS0hjMFR5OA==
  SPRING_JPA_HIBERNATE_DDL_AUTO: dXBkYXRl
  SPRING_REDIS_HOST: MTAuOTYuMTAzLjE0MQ==
  SPRING_REDIS_PORT: NjM3OQ==
  SPRING_REDIS_PASSWORD: c3JXR1cycGY1VA==
  SPRING_CACHE_TYPE: cmVkaXM=
  SPRING_CACHE_REDIS_TIME_TO_LIVE: MzAwMDAw

  SPRING_KAFKA_BOOTSTRAP_SERVERS: MTAuMTExLjY3LjE0ODo5MDky
  SPRING_KAFKA_CONSUMER_GROUP_ID: bXktYXdlc29tZS1hcHA=

  APP_TOKEN_SECRET: dGVzdFNlY3JldFZpYUNvbnRhaW5lcjIwMjE=
  APP_TOKEN_ISSURE: QmFja2VuZFNlcnZpY2U=
kind: Secret
metadata:
  name: backend
  namespace: training
type: Opaque