version: '3'

services:
  backend:
    container_name: backend
    build: .
    image: backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SECRET_DB_HOST}:${SECRET_DB_PORT}/${SECRET_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${SECRET_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SECRET_DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: ${SECRET_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${SECRET_REDIS_PASSWORD}
      SPRING_CACHE_TYPE: redis
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 300000

      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SECRET_KAFKA_HOST}:${SECRET_KAFKA_PORT}
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${SECRET_KAFKA_CONSUMER_GROUP_ID}

      APP_TOKEN_SECRET:  ${SECRET_JWT_SECRET}
      APP_TOKEN_ISSURE: BackendService
  email:
    container_name: email
    build: ../email/
    image: email
    ports:
      - 8082:8082
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SECRET_KAFKA_HOST}:${SECRET_KAFKA_PORT}
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${SECRET_KAFKA_CONSUMER_GROUP_ID}
      SPRING_MAIL_HOST: ${SECRET_MAIL_HOST}
      SPRING_MAIL_PORT: ${SECRET_MAIL_POST}
      SECRET_MAIL_USERNAME: ${SECRET_MAIL_USERNAME}
      SECRET_MAIL_PASSWORD: ${SECRET_MAIL_PASSWORD}
      SPRING_MAIL_PRPPERTIES_MAIL_SMTP_AUTH: ${SECRET_MAIL_PRPPERTIES_MAIL_SMTP_AUTH}
      SPRING_MAIL_PRPPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SECRET_MAIL_PRPPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

      APP_TOKEN_SECRET: ${SECRET_JWT_SECRET}
      APP_TOKEN_ISSURE: BackendService
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
#    volumes:
#      - pg-dataset:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SECRET_DB_PASSWORD}
      POSTGRES_DB: ${SECRET_DB_NAME}
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${SECRET_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${SECRET_PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${SECRET_PGADMIN_PORT}

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
  redis:
    image: 'bitnami/redis'
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${SECRET_REDIS_PASSWORD}


# https://mrchoke.medium.com/phpmyadmin-%E0%B8%A0%E0%B8%B2%E0%B8%84%E0%B8%9E%E0%B8%B4%E0%B8%A8%E0%B8%94%E0%B8%B2%E0%B8%A3-675b6f9ce9f
# เวลาต่อ postgres ใช้ ip 172.17.0.1