version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - pg-dataset:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: syspass
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inw.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
  redis:
    image: 'bitnami/redis'
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: syspass


# https://mrchoke.medium.com/phpmyadmin-%E0%B8%A0%E0%B8%B2%E0%B8%84%E0%B8%9E%E0%B8%B4%E0%B8%A8%E0%B8%94%E0%B8%B2%E0%B8%A3-675b6f9ce9f
# เวลาต่อ postgres ใช้ ip 172.17.0.1