version: '3'

services:
  backend:
    container_name: backend
    build: .
    image: backend
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/backend
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: syspass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: syspass
      SPRING_CACHE_TYPE: redis
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 300000

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: my-awesome-app

      APP_TOKEN_SECRET: m#MySecret2021GGWP
      APP_TOKEN_ISSURE: BackendService

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
#    volumes:
#      - pg-dataset:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: syspass
      POSTGRES_DB: backend
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inw.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
  redis:
    image: 'bitnami/redis'
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: syspass


# https://mrchoke.medium.com/phpmyadmin-%E0%B8%A0%E0%B8%B2%E0%B8%84%E0%B8%9E%E0%B8%B4%E0%B8%A8%E0%B8%94%E0%B8%B2%E0%B8%A3-675b6f9ce9f
# เวลาต่อ postgres ใช้ ip 172.17.0.1