server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9092
    hostname
    consumer:
      group-id: "my-awesome-app"
  mail:
    host: smtp.gmail.com
    port: 587
    username: army@xhub.trade
    password: dcvblgfeseohlipn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
  #     if production mode = none
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: localhost
    port: 6379
    password: syspass
#    url:
  cache:
    type: redis
    redis:
      time-to-live: 300000
app:
  token:
    secret: m#MySecret2021GGWP
    issuer: BackendService