spring:
  datasource:
    url: jdbc:postgres://locahost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
